services:
  file3:
    image: continuumio/miniconda3
    container_name: file3
    ports:
      - "9001:9001" # 映射容器的8000端口到主机
    # restart: always # 容器重启策略，服务宕机时自动重启
    stdin_open: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - .:/file3 # 映射 requirements.txt 文件到容器
    # 安装依赖并启动服务
    command: >
      sh -c "
        cd /file3 &&
        pip install -r package.txt &&
        conda install -c conda-forge cupy cudatoolkit=11.8 -y &&
        conda install -c conda-forge pythonocc-core=7.8.1.1 -y &&
        python main.py
      "
